"""empty message

Revision ID: 3fd0b0170eb5
Revises: 
Create Date: 2019-09-27 11:36:56.778537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd0b0170eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stellar_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('large_celestial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stellar_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stellar_system_id'], ['stellar_system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('small_celestial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stellar_system_id', sa.Integer(), nullable=False),
    sa.Column('large_celestial_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['large_celestial_id'], ['large_celestial.id'], ),
    sa.ForeignKeyConstraint(['stellar_system_id'], ['stellar_system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('small_celestial')
    op.drop_table('large_celestial')
    op.drop_table('stellar_system')
    # ### end Alembic commands ###
