"""empty message

Revision ID: d89027cd58e6
Revises: cc26c21d612f
Create Date: 2019-09-28 08:15:23.158764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89027cd58e6'
down_revision = 'cc26c21d612f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('large_celestial', sa.Column('classification', sa.String(length=10), nullable=False))
    op.add_column('large_celestial', sa.Column('orbital_period', sa.Float(), nullable=True))
    op.add_column('large_celestial', sa.Column('radius', sa.Float(), nullable=False))
    op.add_column('large_celestial', sa.Column('semi_major_axis', sa.Float(), nullable=True))
    op.add_column('small_celestial', sa.Column('classification', sa.String(length=10), nullable=False))
    op.add_column('small_celestial', sa.Column('orbital_period', sa.Float(), nullable=True))
    op.add_column('small_celestial', sa.Column('radius', sa.Float(), nullable=False))
    op.add_column('small_celestial', sa.Column('semi_major_axis', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('small_celestial', 'semi_major_axis')
    op.drop_column('small_celestial', 'radius')
    op.drop_column('small_celestial', 'orbital_period')
    op.drop_column('small_celestial', 'classification')
    op.drop_column('large_celestial', 'semi_major_axis')
    op.drop_column('large_celestial', 'radius')
    op.drop_column('large_celestial', 'orbital_period')
    op.drop_column('large_celestial', 'classification')
    # ### end Alembic commands ###
